# Generated by Django 4.2 on 2023-05-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experimento_Teorico',
            fields=[
                ('experimento_t', models.IntegerField(primary_key=True, serialize=False)),
                ('temp_ebulicao_t', models.FloatField()),
                ('concentracao_t', models.FloatField(default=None)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Experimento_Pratico',
            fields=[
                ('experimento_p', models.IntegerField(primary_key=True, serialize=False)),
                ('temp_ebulicao_p', models.FloatField()),
                ('concentracao_p', models.FloatField(default=None)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aluno')),
            ],
        ),
    ]
