# Generated by Django 3.2.12 on 2023-06-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experimento_Teorico',
        ),
    ]
